apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ssexcfeq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ssexcfeq:c6e275d82d2bbf2298e5724a5a837693c7c2a381@sha256:af7e004b9d2cd3c17f6bca0bfa68fe733fccba5152c4ecd8f475441ab0fea7d0
          name: container-image
